//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanUpLogs.Console.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanUpLogs.Console.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##############################################################################################
        ///###############################################################################################
        ///]0;kurs@localhost:~[kurs@localhost ~]$ sudo -s[K[Ksu -
        ///[sudo] Passwort für kurs: 
        ///]0;root@localhost:~[root@localhost ~]# # ls -lisah[K[K[K[Ka
        ///]0;root@localhost:~[root@localhost ~]# s -lisa[K[K[Ka
        ///]0;root@localhost:~[root@localhost ~]# sudo -s        ///[K[root@localhost ~]#         ///[K[root@localhost ~]# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdatei {
            get {
                return ResourceManager.GetString("testdatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##############################################################################################
        ///###############################################################################################
        ///[kurs@localhost ~]$ sudo su -
        ///[sudo] Passwort für kurs: 
        ///[root@localhost ~]# # ls -la
        ///[root@localhost ~]# s -la
        ///[root@localhost ~]# sudo -s
        ///[root@localhost ~]# 
        ///[root@localhost ~]# env
        ///[root@localhost ~]# echo $USER
        ///dr-xr-x---.  5 root root  184  4. Okt 11:29 .
        ///dr-xr-xr-x. 17 root root  224  1. Okt 17:44 ..
        ///-rw-------.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdatei_SOLL {
            get {
                return ResourceManager.GetString("testdatei_SOLL", resourceCulture);
            }
        }
    }
}
